#BOUNDARY BEGIN
sort	sequential dichtotome
identifier	10% RRR
type	103
type1error	5.0
oisType	603
manualOIS	0.0
type2error	20.0
interventionEffectType	204
interventionEffect	13.7
controlEffect	16.0
timeAxisScaling	302
heterogeneityCorrection	401
heterogeneityCorrectionValue	0.0
alphaSpendingFunction	501
#GRAPH BEGIN
id	10% RRR
color	255	0	0
graphLineType	Full
graphIconType	Diamond Fill
graphIconSize	5
doShow	true
doSmooth	false
#GRAPH END
#BOUNDARY END

#BOUNDARY BEGIN
sort	sequential dichotome
identifier	10% RRR IW
type	103
type1error	5.0
oisType	603
manualOIS	0.0
type2error	78.0
interventionEffectType	204
interventionEffect	13.7
controlEffect	16.0
timeAxisScaling	302
heterogeneityCorrection	401
heterogeneityCorrectionValue	0.0
alphaSpendingFunction	501
betaSpendingFunction	802
#GRAPH BEGIN
id	10% RRR IW
color	255	0	0
graphLineType	Full
graphIconType	Diamond Fill
graphIconSize	5
doShow	true
doSmooth	false
#GRAPH END
#BOUNDARY END

#BOUNDARY BEGIN
sort	conventional
identifier	5% type 1 error risk
type	103
type1error	5.0
#GRAPH BEGIN
id	5% type 1 error risk
color	155	0	0
graphLineType	Full
graphIconType	Diamond Fill
graphIconSize	5
doShow	true
#GRAPH END
#BOUNDARY END

